services:
  app:
    container_name: "app"
    image: "jboss/wildfly-admin:latest"
    mem_limit: 2g
    mem_reservation: 128M
    cpus: 0.5
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=Admin#70365
      - DB_NAME=biblioteca
      - DB_USER=mysql
      - DB_PASS=mysql
      - DB_URI=db:3306
    volumes:
      - ./db/wildfly:/wildfly/ # wildfly
    depends_on:
      - db
    ports:
      - "8080:8080" # application
      - "9990:9990" # admin console
      
  db:
    container_name: "db"
    image: "mysql:8.1.0"
    mem_limit: 1g
    mem_reservation: 128M
    cpus: 0.5
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=biblioteca
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=supersecret
      - HOST_CACHE_SIZE=0
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/mysql/data/:/var/lib/mysql/ # data storage
    ports:
      - "3306:3306"
      
volumes:  
  db:
    driver: local
    driver_opts:
      type: disk
      size: 1GB
  
networks:
  default:
    driver: bridge
